project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Yameng Zhang"
  site-url: https://lianyujun.github.io
  favicon: images/site-logo.svg
  repo-url: https://github.com/lianyujun/lianyujun.github.io
  
  page-footer:
    center: |
      © Yameng Zhang | Last updated: April 2026
    
  navbar: 
    background: "#002FA7"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "News"
        href: news.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细