---
title: "Publications"
toc: false
---

1. **Yameng Zhang**, Dianye Huang, Xiangyu Chu, K. W. Samuel Au, Zhongliang Jiang. Enhanced Freehand 3D Ultrasound Imaging with Fusion of White-Light and Ultrasound Imaging. *Hamlyn Symposium on Medical Robotics*, 2026. [Paper](https://www.hamlynsymposium.org/wp-content/uploads/2026/06/HSMR26-Proceedings-web.pdf)

1. Nigel Nelson, ..., **Yameng Zhang**, et al. Open-H-Embodiment: A Large-Scale Dataset for Enabling Foundation Models in Medical Robotics. *arXiv preprint arXiv:2604.21017*, 2026. [Paper](https://arxiv.org/abs/2604.21017)

1. Yizhao Qian, Jiayuan Luo, **Yameng Zhang**, Kai Long, Yixuan Yuan, Max Q.-H. Meng, Li Liu. Symmetry-Optimized Image Guidance and Biomechanics-Driven Force Measurement for Robotic Ultrasound: A Control Framework Enhancing Sonographic Quality. *IEEE Transactions on Instrumentation and Measurement (TIM)*, 2026. [Paper](https://ieeexplore.ieee.org/document/11449287)

1. **Yameng Zhang**, Dianye Huang, Max Q.-H. Meng, Nassir Navab, Zhongliang Jiang. Freehand 3D Ultrasound Imaging: Sim-in-the-Loop Probe Pose Optimization via Visual Servoing. *IEEE/ASME Transactions on Mechatronics (TMECH)*, 2025. [Paper](https://ieeexplore.ieee.org/document/11231023) [Video](https://youtu.be/hNNVrdFW-KE)

1. Xuesong Li, Dianye Huang, **Yameng Zhang**, Nassir Navab, Zhongliang Jiang. Semantic Scene Graph for Ultrasound Image Explanation and Scanning Guidance. *International Conference on Medical Image Computing and Computer-Assisted Intervention (MICCAI)*, 2025. [Paper](https://arxiv.org/abs/2506.19683)

1. Yizhao Qian, **Yameng Zhang**, Max Q.-H. Meng, Li Liu. Autonomous In-plane Normal Positioning in Robotic Ultrasound Scanning. *IEEE International Conference on Robotics and Biomimetics (ROBIO)*, 2024. [Paper](https://ieeexplore.ieee.org/abstract/document/10907531?casa_token=PXX4PWpx6JQAAAAA:z1msLyxYk5A9hixw9rRqLSny-3h_X09bo9L6H7Qw7KmpkrFFYNVpZu-vk3-XCTPlml58ZdSs)

1. **Yameng Zhang**, Yizhao Qian, Li Liu, Max Q.-H. Meng. Model-Free Magnetic Servoing Control: Leveraging Raw Magnetic Data for Robotic Manipulation. *IEEE/ASME Transactions on Mechatronics (TMECH)*, 2024. [Paper](https://ieeexplore.ieee.org/document/10606057) [Video](https://youtu.be/FUcQBJyQk9Q)

1. **Yameng Zhang**, Li Liu, Max Q.-H. Meng. Robotic Simulation Method for Magnetic Positioning and Navigation. *IEEE International Conference on Robotics and Automation (ICRA) Workshop on C4SR+*, 2024. (Third Place-Best Poster Award)

1. Qi Zhang, Han Xu, Detian Zeng, **Yameng Zhang**, Li Liu. Real-Time Positioning of a Magnetically-Driven Endoscopic Laser End-Effector under Electromagnetic Interference. *IEEE Transactions on Instrumentation and Measurement (TIM)*, 2024. [Paper](https://ieeexplore.ieee.org/document/10700776)

1. **Yameng Zhang**, Ao Xu, Yuhan Chen, Max Q.-H. Meng, Li Liu. Multi-Scale Visual Servoing Framework for Optical Microscopy based on SIFT Matching. *IEEE Robotics and Automation Letters (RA-L)*, 2023. (Presented at IEEE ICRA 2024) [Paper](https://ieeexplore.ieee.org/abstract/document/10287399) [Video](https://youtu.be/WnDRxQ86DOk)

1. **Yameng Zhang**, Max Q.-H. Meng, Li Liu. Design and Control of a Compact Electromagnetically Driven Laser Scanner for Robotic-Assisted Endoscopic Microsurgeries. *IEEE Transactions on Automation Science and Engineering (T-ASE)*, 2023. [Paper](https://ieeexplore.ieee.org/abstract/document/10278108) [Video](https://youtu.be/JUwyltlM_qY)

1. **Yameng Zhang**<sup>&dagger;</sup>, Long Bai<sup>&dagger;</sup>, Li Liu, Hongliang Ren, Max Q.-H. Meng. Deep Reinforcement Learning-Based Control for Stomach Coverage Scanning of Wireless Capsule Endoscopy. *IEEE International Conference on Robotics and Biomimetics (ROBIO)*, 2022. [Paper](https://ieeexplore.ieee.org/document/10012018)

1. Xi Zhang, **Yameng Zhang**, Zhimin Zhang, Mayan Li. Mode Conversion and Structure Optimization of Quadrature Coils for Electric Vehicles Wireless Power Transfer. *IEEE Transactions on Energy Conversion (T-EC)*, 2020. [Paper](https://ieeexplore.ieee.org/abstract/document/8988223)

1. **Yameng Zhang**, Xi Zhang, Chong Zhu, Dongpu Cao. Calculation Model of Mutual Coupling Between Two Ferrite-cored Square Coils in Wireless Power Application for Electric Vehicles. *Journal of Physics: Conference Series*, 2020. [Paper](https://iopscience.iop.org/article/10.1088/1742-6596/1619/1/012004/meta)

1. **Yameng Zhang**, Xi Zhang, Zhimin Zhang. Impedance Detection-Based Multi-Channel Automatic Tuning Metal Object Detection System for Wireless Charging Device. *Advanced Technology of Electrical Engineering and Energy*, 2020. [Paper](https://ateee.iee.ac.cn/CN/10.12067/ATEEE1908058)